# Generated by Django 3.2.6 on 2024-07-03 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Literature-Story', 'Literature-Story'), ('Poem', 'Poem'), ('Novel', 'Novel'), ('Article', 'Article'), ('Journals', 'Journals')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('open', 'Open'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile/default.jpg', upload_to='Profile')),
                ('qualification', models.CharField(default='Not Provided', max_length=100)),
                ('phone_number', models.CharField(default='Not Provided', max_length=20)),
                ('address', models.CharField(default='Not Provided', max_length=255)),
                ('location', models.CharField(default='Not Provided', max_length=100)),
                ('state', models.CharField(default='Not Provided', max_length=100)),
                ('city', models.CharField(default='Not Provided', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='name', max_length=150)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone', models.CharField(default='Not Provided', max_length=50)),
                ('address', models.CharField(default='Not Provided', max_length=255)),
                ('qual', models.CharField(default='Not Provided', max_length=100)),
                ('field', models.CharField(default='Default Value', max_length=100)),
                ('img', models.ImageField(upload_to='Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling_mark', models.FloatField(default=0)),
                ('plagiarism_mark', models.FloatField(default=0)),
                ('grammar_mark', models.FloatField(default=0)),
                ('total_mark', models.FloatField(default=0)),
                ('reviewed_by', models.CharField(default='', max_length=150)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.writingsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_against', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
