# Generated by Django 3.2.6 on 2024-07-03 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
