# Generated by Django 3.2.6 on 2024-07-03 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0002_master_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.master')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.userreg')),
            ],
        ),
    ]
