# Generated by Django 3.2.6 on 2024-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('UserReg', 'UserReg'), ('Master', 'Master')], default='User', max_length=10),
            preserve_default=False,
        ),
    ]
