# Generated by Django 3.2.6 on 2024-07-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0004_chatmessage_sender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_master', to='pen.master'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_user', to='pen.userreg'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pen.master'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pen.userreg'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
