# Generated by Django 3.2.6 on 2024-07-04 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0005_auto_20240704_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='pen.master'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='pen.userreg'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='pen.master'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='pen.userreg'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
