# Generated by Django 3.2.6 on 2024-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0007_alter_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.TextField(default='Not Provided'),
        ),
    ]
