# Generated by Django 3.2.6 on 2024-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0008_master_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
