# Generated by Django 3.2.6 on 2024-07-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0010_master_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('open', 'Open'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
