# Generated by Django 3.2.6 on 2024-07-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0011_alter_writingsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsubmission',
            name='category',
            field=models.CharField(choices=[('Story', 'Story'), ('Poet', 'Poet'), ('Novel', 'Novel'), ('Article', 'Article'), ('Journals', 'Journals')], max_length=20),
        ),
    ]
