# Generated by Django 3.2.6 on 2024-07-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0012_alter_writingsubmission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsubmission',
            name='category',
            field=models.CharField(choices=[('Story', 'Story'), ('Poem', 'Poem'), ('Novel', 'Novel'), ('Article', 'Article'), ('Journals', 'Journals')], max_length=20),
        ),
    ]
