# Generated by Django 3.2.6 on 2024-07-10 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0013_alter_writingsubmission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
